---
- name: Install Docker
  hosts: clients
  gather_facts: no
  become: true


  tasks:

         
  - name: Install python3 apt
    apt:
      name:
         - python3-apt
      state: present        

  - name: Update the apt package index
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Upgrade packages
    apt: 
      upgrade: dist 
      force_apt_get: yes

  - name: Install dependencies    
    apt:
      name:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - software-properties-common
         - lsb-release
         - python3-pip
         - git
      state: present

      
  - name: Add gpg key 
    apt_key: 
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
        
 

  - name: Add docker repo
    apt_repository: 
        repo:  deb https://download.docker.com/linux/ubuntu focal stable
        state: present
       

  - name: "Install Docker"
    apt:
      name:
         - docker-ce 
         - docker-ce-cli 
         - containerd.io
         - docker-compose  
      state: present
      update_cache: yes

  
  - name: Download docker-compose
    get_url:
        url : https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '+x'            
  


  - name: Clone wekan git repo
    git:
      repo: https://github.com/wekan/wekan
      dest: /home/wekan/


  - name: Create and start services
    docker_compose:
        project_src: /home/wekan/
        state: present



   